#
# Autogenerated file, DO NOT EDIT
#

#
# Files matching regexps:
#
#  /home/francesco/Sviluppo/grammar-extractors/grammar-extractors/yaxx-to-grammar.in
#

AC_DEFUN([PERL_AUTOFRISK_CHECKS],[
    #AX_PROG_PERL_MODULES([Getopt::Long],[],[])
    #AX_PROG_PERL_MODULES([warnings],[],[])
    #AX_PROG_PERL_MODULES([strict],[],[])
    #AX_PROG_PERL_MODULES([diagnostics],[],[])
    #AX_PROG_PERL_MODULES([Text::Balanced],[],[])
])

AC_DEFUN([PERL_AUTOFRISK_SUMMARY],[
])
